/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatLayoutRouteImport } from './routes/_chat-layout'
import { Route as ChatLayoutIndexRouteImport } from './routes/_chat-layout/index'

const ChatLayoutRoute = ChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLayoutIndexRoute = ChatLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat-layout': typeof ChatLayoutRouteWithChildren
  '/_chat-layout/': typeof ChatLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_chat-layout' | '/_chat-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat-layout': {
      id: '/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat-layout/': {
      id: '/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatLayoutIndexRouteImport
      parentRoute: typeof ChatLayoutRoute
    }
  }
}

interface ChatLayoutRouteChildren {
  ChatLayoutIndexRoute: typeof ChatLayoutIndexRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatLayoutIndexRoute: ChatLayoutIndexRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(
  ChatLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
